export interface GazetteerEntry {
  city: string;
  iata: string;
  country: string;
  aliases?: string[];
}

/** A compact gazetteer good enough for the offline heuristic engine. */
export const GAZETTEER: GazetteerEntry[] = [
  { city: "New York", iata: "JFK", country: "United States", aliases: ["nyc", "new york city", "manhattan"] },
  { city: "Newark", iata: "EWR", country: "United States" },
  { city: "Boston", iata: "BOS", country: "United States" },
  { city: "Washington", iata: "IAD", country: "United States", aliases: ["washington dc", "dc"] },
  { city: "Chicago", iata: "ORD", country: "United States" },
  { city: "Atlanta", iata: "ATL", country: "United States" },
  { city: "Miami", iata: "MIA", country: "United States" },
  { city: "Orlando", iata: "MCO", country: "United States" },
  { city: "Dallas", iata: "DFW", country: "United States" },
  { city: "Houston", iata: "IAH", country: "United States" },
  { city: "Denver", iata: "DEN", country: "United States" },
  { city: "Seattle", iata: "SEA", country: "United States" },
  { city: "San Francisco", iata: "SFO", country: "United States", aliases: ["sf", "bay area"] },
  { city: "Los Angeles", iata: "LAX", country: "United States", aliases: ["la"] },
  { city: "San Diego", iata: "SAN", country: "United States" },
  { city: "Las Vegas", iata: "LAS", country: "United States", aliases: ["vegas"] },
  { city: "Phoenix", iata: "PHX", country: "United States" },
  { city: "Austin", iata: "AUS", country: "United States" },
  { city: "Nashville", iata: "BNA", country: "United States" },
  { city: "New Orleans", iata: "MSY", country: "United States" },
  { city: "Honolulu", iata: "HNL", country: "United States", aliases: ["oahu"] },
  { city: "Maui", iata: "OGG", country: "United States" },
  { city: "Anchorage", iata: "ANC", country: "United States" },
  { city: "Toronto", iata: "YYZ", country: "Canada" },
  { city: "Vancouver", iata: "YVR", country: "Canada" },
  { city: "Montreal", iata: "YUL", country: "Canada" },
  { city: "Mexico City", iata: "MEX", country: "Mexico" },
  { city: "Cancun", iata: "CUN", country: "Mexico", aliases: ["cancún", "riviera maya", "tulum"] },
  { city: "Cabo San Lucas", iata: "SJD", country: "Mexico", aliases: ["los cabos", "cabo"] },
  { city: "Havana", iata: "HAV", country: "Cuba" },
  { city: "Nassau", iata: "NAS", country: "Bahamas", aliases: ["bahamas"] },
  { city: "Montego Bay", iata: "MBJ", country: "Jamaica", aliases: ["jamaica"] },
  { city: "Punta Cana", iata: "PUJ", country: "Dominican Republic" },
  { city: "San Juan", iata: "SJU", country: "Puerto Rico", aliases: ["puerto rico"] },
  { city: "Bridgetown", iata: "BGI", country: "Barbados", aliases: ["barbados"] },
  { city: "San Jose", iata: "SJO", country: "Costa Rica", aliases: ["costa rica"] },
  { city: "Panama City", iata: "PTY", country: "Panama" },
  { city: "Bogota", iata: "BOG", country: "Colombia", aliases: ["bogotá"] },
  { city: "Cartagena", iata: "CTG", country: "Colombia" },
  { city: "Lima", iata: "LIM", country: "Peru", aliases: ["cusco", "machu picchu"] },
  { city: "Santiago", iata: "SCL", country: "Chile" },
  { city: "Buenos Aires", iata: "EZE", country: "Argentina" },
  { city: "Rio de Janeiro", iata: "GIG", country: "Brazil", aliases: ["rio"] },
  { city: "Sao Paulo", iata: "GRU", country: "Brazil", aliases: ["são paulo"] },
  { city: "London", iata: "LHR", country: "United Kingdom" },
  { city: "Manchester", iata: "MAN", country: "United Kingdom" },
  { city: "Edinburgh", iata: "EDI", country: "United Kingdom", aliases: ["scotland"] },
  { city: "Dublin", iata: "DUB", country: "Ireland", aliases: ["ireland"] },
  { city: "Paris", iata: "CDG", country: "France" },
  { city: "Nice", iata: "NCE", country: "France", aliases: ["french riviera", "cote d'azur"] },
  { city: "Lyon", iata: "LYS", country: "France" },
  { city: "Amsterdam", iata: "AMS", country: "Netherlands" },
  { city: "Brussels", iata: "BRU", country: "Belgium" },
  { city: "Berlin", iata: "BER", country: "Germany" },
  { city: "Munich", iata: "MUC", country: "Germany" },
  { city: "Frankfurt", iata: "FRA", country: "Germany" },
  { city: "Zurich", iata: "ZRH", country: "Switzerland", aliases: ["zürich"] },
  { city: "Geneva", iata: "GVA", country: "Switzerland" },
  { city: "Vienna", iata: "VIE", country: "Austria" },
  { city: "Prague", iata: "PRG", country: "Czechia" },
  { city: "Budapest", iata: "BUD", country: "Hungary" },
  { city: "Warsaw", iata: "WAW", country: "Poland" },
  { city: "Copenhagen", iata: "CPH", country: "Denmark" },
  { city: "Stockholm", iata: "ARN", country: "Sweden" },
  { city: "Oslo", iata: "OSL", country: "Norway" },
  { city: "Helsinki", iata: "HEL", country: "Finland" },
  { city: "Reykjavik", iata: "KEF", country: "Iceland", aliases: ["iceland", "reykjavík"] },
  { city: "Lisbon", iata: "LIS", country: "Portugal" },
  { city: "Porto", iata: "OPO", country: "Portugal" },
  { city: "Madrid", iata: "MAD", country: "Spain" },
  { city: "Barcelona", iata: "BCN", country: "Spain" },
  { city: "Seville", iata: "SVQ", country: "Spain", aliases: ["sevilla"] },
  { city: "Palma", iata: "PMI", country: "Spain", aliases: ["mallorca", "majorca"] },
  { city: "Ibiza", iata: "IBZ", country: "Spain" },
  { city: "Rome", iata: "FCO", country: "Italy" },
  { city: "Milan", iata: "MXP", country: "Italy" },
  { city: "Venice", iata: "VCE", country: "Italy" },
  { city: "Florence", iata: "FLR", country: "Italy", aliases: ["tuscany", "firenze"] },
  { city: "Naples", iata: "NAP", country: "Italy", aliases: ["amalfi", "amalfi coast", "positano"] },
  { city: "Catania", iata: "CTA", country: "Italy", aliases: ["sicily"] },
  { city: "Athens", iata: "ATH", country: "Greece" },
  { city: "Santorini", iata: "JTR", country: "Greece" },
  { city: "Mykonos", iata: "JMK", country: "Greece" },
  { city: "Crete", iata: "HER", country: "Greece", aliases: ["heraklion"] },
  { city: "Istanbul", iata: "IST", country: "Turkey" },
  { city: "Split", iata: "SPU", country: "Croatia", aliases: ["croatia", "dalmatia"] },
  { city: "Dubrovnik", iata: "DBV", country: "Croatia" },
  { city: "Ljubljana", iata: "LJU", country: "Slovenia", aliases: ["slovenia"] },
  { city: "Marrakech", iata: "RAK", country: "Morocco", aliases: ["marrakesh", "morocco"] },
  { city: "Cairo", iata: "CAI", country: "Egypt", aliases: ["egypt"] },
  { city: "Cape Town", iata: "CPT", country: "South Africa" },
  { city: "Johannesburg", iata: "JNB", country: "South Africa" },
  { city: "Nairobi", iata: "NBO", country: "Kenya", aliases: ["kenya", "masai mara", "maasai mara"] },
  { city: "Kilimanjaro", iata: "JRO", country: "Tanzania", aliases: ["tanzania", "serengeti"] },
  { city: "Zanzibar", iata: "ZNZ", country: "Tanzania" },
  { city: "Dubai", iata: "DXB", country: "United Arab Emirates" },
  { city: "Abu Dhabi", iata: "AUH", country: "United Arab Emirates" },
  { city: "Doha", iata: "DOH", country: "Qatar" },
  { city: "Tel Aviv", iata: "TLV", country: "Israel" },
  { city: "Amman", iata: "AMM", country: "Jordan", aliases: ["jordan", "petra"] },
  { city: "Delhi", iata: "DEL", country: "India", aliases: ["new delhi"] },
  { city: "Mumbai", iata: "BOM", country: "India" },
  { city: "Bengaluru", iata: "BLR", country: "India", aliases: ["bangalore"] },
  { city: "Goa", iata: "GOI", country: "India" },
  { city: "Jaipur", iata: "JAI", country: "India", aliases: ["rajasthan"] },
  { city: "Kochi", iata: "COK", country: "India", aliases: ["kerala"] },
  { city: "Chennai", iata: "MAA", country: "India" },
  { city: "Hyderabad", iata: "HYD", country: "India" },
  { city: "Colombo", iata: "CMB", country: "Sri Lanka", aliases: ["sri lanka"] },
  { city: "Male", iata: "MLE", country: "Maldives", aliases: ["maldives", "malé"] },
  { city: "Kathmandu", iata: "KTM", country: "Nepal", aliases: ["nepal"] },
  { city: "Bangkok", iata: "BKK", country: "Thailand", aliases: ["thailand"] },
  { city: "Phuket", iata: "HKT", country: "Thailand" },
  { city: "Krabi", iata: "KBV", country: "Thailand" },
  { city: "Chiang Mai", iata: "CNX", country: "Thailand" },
  { city: "Hanoi", iata: "HAN", country: "Vietnam", aliases: ["vietnam"] },
  { city: "Ho Chi Minh City", iata: "SGN", country: "Vietnam", aliases: ["saigon"] },
  { city: "Siem Reap", iata: "REP", country: "Cambodia", aliases: ["cambodia", "angkor wat"] },
  { city: "Singapore", iata: "SIN", country: "Singapore" },
  { city: "Kuala Lumpur", iata: "KUL", country: "Malaysia" },
  { city: "Bali", iata: "DPS", country: "Indonesia", aliases: ["denpasar", "ubud", "seminyak"] },
  { city: "Jakarta", iata: "CGK", country: "Indonesia" },
  { city: "Manila", iata: "MNL", country: "Philippines" },
  { city: "Hong Kong", iata: "HKG", country: "Hong Kong" },
  { city: "Taipei", iata: "TPE", country: "Taiwan" },
  { city: "Shanghai", iata: "PVG", country: "China" },
  { city: "Beijing", iata: "PEK", country: "China" },
  { city: "Seoul", iata: "ICN", country: "South Korea" },
  { city: "Tokyo", iata: "HND", country: "Japan" },
  { city: "Osaka", iata: "KIX", country: "Japan" },
  { city: "Kyoto", iata: "KIX", country: "Japan" },
  { city: "Sapporo", iata: "CTS", country: "Japan", aliases: ["niseko", "hokkaido"] },
  { city: "Sydney", iata: "SYD", country: "Australia" },
  { city: "Melbourne", iata: "MEL", country: "Australia" },
  { city: "Brisbane", iata: "BNE", country: "Australia" },
  { city: "Perth", iata: "PER", country: "Australia" },
  { city: "Cairns", iata: "CNS", country: "Australia", aliases: ["great barrier reef"] },
  { city: "Auckland", iata: "AKL", country: "New Zealand", aliases: ["new zealand"] },
  { city: "Queenstown", iata: "ZQN", country: "New Zealand" },
  { city: "Nadi", iata: "NAN", country: "Fiji", aliases: ["fiji"] },
  { city: "Papeete", iata: "PPT", country: "French Polynesia", aliases: ["tahiti", "bora bora"] },
];

export const AIRLINES = [
  "Emirates", "Qatar Airways", "Singapore Airlines", "Cathay Pacific", "ANA", "JAL",
  "Japan Airlines", "Lufthansa", "Swiss", "Air France", "KLM", "British Airways",
  "Virgin Atlantic", "Iberia", "TAP", "Turkish Airlines", "Etihad", "Delta",
  "United", "American Airlines", "Alaska Airlines", "JetBlue", "Southwest",
  "Air Canada", "Qantas", "Air New Zealand", "Ryanair", "easyJet", "Vueling",
  "IndiGo", "Air India", "Vistara", "Aer Lingus", "Finnair", "SAS", "Norwegian",
  "Icelandair", "Copa", "LATAM", "Avianca", "Ethiopian Airlines", "Kenya Airways",
];

export const AMENITY_KEYWORDS: Record<string, string[]> = {
  "Swimming pool": ["pool", "infinity pool", "rooftop pool"],
  "Free WiFi": ["wifi", "wi-fi", "internet"],
  Spa: ["spa", "massage", "hammam", "onsen"],
  Gym: ["gym", "fitness", "peloton"],
  "Breakfast included": ["breakfast included", "with breakfast", "free breakfast"],
  "Airport shuttle": ["shuttle"],
  Parking: ["parking", "valet"],
  "Kitchenette": ["kitchen", "kitchenette", "self catering", "self-catering"],
  "Beach access": ["beachfront", "beach access", "on the beach", "steps from the beach"],
  "Ocean view": ["ocean view", "sea view", "sea-view", "oceanfront"],
  "Kids club": ["kids club", "kids' club", "childcare", "babysitting"],
  "Pet friendly": ["pet friendly", "pet-friendly", "dog friendly"],
  "Work desk": ["work desk", "desk", "workspace"],
  "Connecting rooms": ["connecting rooms", "adjoining rooms"],
  "Air conditioning": ["air conditioning", "air-con", "a/c"],
  "Late checkout": ["late checkout", "late check-out"],
  "Club lounge": ["club lounge", "executive lounge", "lounge access"],
};

export const ACTIVITY_KEYWORDS: Record<string, string[]> = {
  Snorkelling: ["snorkel", "snorkelling", "snorkeling"],
  Scuba: ["scuba", "diving", "dive"],
  Surfing: ["surf", "surfing"],
  Skiing: ["ski", "skiing", "snowboard", "powder"],
  Hiking: ["hike", "hiking", "trek", "trekking", "trail"],
  "Safari / game drives": ["safari", "game drive", "big five"],
  "Food & wine tours": ["food tour", "wine tour", "winery", "vineyard", "tasting menu", "cooking class"],
  "Museums & galleries": ["museum", "gallery", "louvre", "art"],
  "Historical sites": ["ruins", "temple", "castle", "old town", "heritage", "pyramids"],
  Nightlife: ["nightlife", "clubs", "bars", "party"],
  Shopping: ["shopping", "boutiques", "markets", "souk"],
  "Theme parks": ["disney", "universal", "theme park", "legoland"],
  Golf: ["golf", "tee time"],
  Cruise: ["cruise", "sailing", "catamaran", "yacht"],
  "Hot air balloon": ["hot air balloon", "balloon ride"],
  "Northern lights": ["northern lights", "aurora"],
  "Yoga & wellness": ["yoga", "wellness", "retreat", "meditation"],
  "Photography": ["photography", "photo tour"],
};

export const DIET_KEYWORDS: Record<string, string[]> = {
  Vegetarian: ["vegetarian", "veggie"],
  Vegan: ["vegan"],
  "Gluten-free": ["gluten free", "gluten-free", "celiac", "coeliac"],
  Halal: ["halal"],
  Kosher: ["kosher"],
  "Nut allergy": ["nut allergy", "peanut allergy", "nut-free"],
  "Dairy-free": ["dairy free", "dairy-free", "lactose"],
  "Shellfish allergy": ["shellfish allergy", "seafood allergy"],
};

export const ACCESS_KEYWORDS: Record<string, string[]> = {
  "Step-free access": ["wheelchair", "step free", "step-free", "accessible room", "no stairs"],
  "Mobility assistance": ["mobility", "walker", "limited mobility", "airport assistance"],
  "Elevator required": ["elevator", "lift required", "ground floor"],
  "Service animal": ["service animal", "guide dog"],
};
